#!/bin/bash

kubectl --server="172.19.130.162:8080"  --namespace=kube-system create -f /data/deploy/source/binary/kubernetes/cluster/addons/registry/registry-pv.yaml
kubectl --server="172.19.130.162:8080"  --namespace=kube-system create -f /data/deploy/source/binary/kubernetes/cluster/addons/registry/registry-pvc.yaml
kubectl --server="172.19.130.162:8080"  --namespace=kube-system create -f /data/deploy/source/binary/kubernetes/cluster/addons/registry/registry-rc.yaml
kubectl --server="172.19.130.162:8080"  --namespace=kube-system create -f /data/deploy/source/binary/kubernetes/cluster/addons/registry/registry-svc.yaml
